# Generated by Django 5.2.4 on 2025-08-02 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('poll_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'db_table': 'polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.UUIDField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.polls')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['poll_id', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.UUIDField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.questions')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'db_table': 'options',
                'ordering': ['question_id', 'option_id'],
            },
        ),
        migrations.AddField(
            model_name='polls',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_created', to='polls.user'),
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('vote_id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.options')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='polls.user')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': 'votes',
                'ordering': ['option_id', 'vote_id'],
            },
        ),
    ]
