# Generated by Django 5.2.4 on 2025-08-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_questions_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
